version: "3"

services:
  web:
    container_name: m3u8-scraper
    build:
      dockerfile: ./Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - my_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  my_network:
